/* This file was generated by syncqt. */
#ifndef QT_QTLOCATION_VERSION_H
#define QT_QTLOCATION_VERSION_H

#define QTLOCATION_VERSION_STR "6.10.2"

#define QTLOCATION_VERSION 0x0601002

#endif // QT_QTLOCATION_VERSION_H
