QT.graphswidgets_private.VERSION = 6.10.2
QT.graphswidgets_private.name = QtGraphsWidgets
QT.graphswidgets_private.module =
QT.graphswidgets_private.libs = $$QT_MODULE_LIB_BASE
QT.graphswidgets_private.includes = $$QT_MODULE_INCLUDE_BASE/QtGraphsWidgets/6.10.2 $$QT_MODULE_INCLUDE_BASE/QtGraphsWidgets/6.10.2/QtGraphsWidgets
QT.graphswidgets_private.frameworks = 
QT.graphswidgets_private.depends = graphs_private core_private graphswidgets
QT.graphswidgets_private.uses = 
QT.graphswidgets_private.module_config = v2 staticlib internal_module
QT.graphswidgets_private.enabled_features = 
QT.graphswidgets_private.disabled_features = 
