#ifndef QT_FEATURES_OpcUa_qtopcua_src_opcua_qtopcua_config_h_H
#define QT_FEATURES_OpcUa_qtopcua_src_opcua_qtopcua_config_h_H

#define QT_FEATURE_open62541 1

#define QT_FEATURE_gds 1

#define QT_FEATURE_open62541_security 1


#endif // QT_FEATURES_OpcUa_qtopcua_src_opcua_qtopcua_config_h_H
