//===- ELFWrapper.cpp - ELF 加壳工具（集成到 clang driver）-----------===//
//
//                     The LLVM Compiler Infrastructure
//
// This file is distributed under the University of Illinois Open Source
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//
//
// 本文件实现 ELF 可执行文件加壳功能，直接编译进 clang.exe：
// 1. 读取原始 ELF 文件
// 2. 使用 ChaCha20 加密
// 3. 生成 payload.h (C 头文件，包含加密后的字节数组)
// 4. 生成 loader.cpp 壳源码
// 5. 调用 clang 自身编译壳程序（最高强度混淆）
// 6. 替换输出为加壳后的可执行文件
//
//===----------------------------------------------------------------------===//

#include "clang/Driver/ELFWrapper.h"
#include "clang/Driver/Driver.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/Compression.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Program.h"
#include "llvm/Support/raw_ostream.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>
#include <fstream>
#include <random>

using namespace llvm;
using namespace clang::driver;

// ============================================================================
// ChaCha20 实现
// ============================================================================

static inline uint32_t rotl32(uint32_t v, int n) {
  return (v << n) | (v >> (32 - n));
}

static inline void qr(uint32_t *s, int a, int b, int c, int d) {
  s[a] += s[b]; s[d] ^= s[a]; s[d] = rotl32(s[d], 16);
  s[c] += s[d]; s[b] ^= s[c]; s[b] = rotl32(s[b], 12);
  s[a] += s[b]; s[d] ^= s[a]; s[d] = rotl32(s[d], 8);
  s[c] += s[d]; s[b] ^= s[c]; s[b] = rotl32(s[b], 7);
}

static void chacha20_block(const uint32_t key[8], uint32_t counter,
                           const uint32_t nonce[3], uint8_t out[64]) {
  uint32_t s[16] = {
      0x61707865, 0x3320646e, 0x79622d32, 0x6b206574,
      key[0], key[1], key[2], key[3],
      key[4], key[5], key[6], key[7],
      counter,
      nonce[0], nonce[1], nonce[2]};

  uint32_t w[16];
  memcpy(w, s, sizeof(w));

  for (int i = 0; i < 10; i++) {
    qr(w, 0, 4, 8, 12);
    qr(w, 1, 5, 9, 13);
    qr(w, 2, 6, 10, 14);
    qr(w, 3, 7, 11, 15);
    qr(w, 0, 5, 10, 15);
    qr(w, 1, 6, 11, 12);
    qr(w, 2, 7, 8, 13);
    qr(w, 3, 4, 9, 14);
  }

  for (int i = 0; i < 16; i++) {
    uint32_t val = w[i] + s[i];
    out[i * 4 + 0] = (uint8_t)(val);
    out[i * 4 + 1] = (uint8_t)(val >> 8);
    out[i * 4 + 2] = (uint8_t)(val >> 16);
    out[i * 4 + 3] = (uint8_t)(val >> 24);
  }
}

static size_t chacha20_encrypt(const uint8_t *input, size_t input_len,
                               const uint8_t key[32], const uint8_t nonce[12],
                               uint8_t *output) {
  uint32_t k[8], n[3];
  for (int i = 0; i < 8; i++)
    k[i] = (uint32_t)key[i * 4] | ((uint32_t)key[i * 4 + 1] << 8) |
           ((uint32_t)key[i * 4 + 2] << 16) | ((uint32_t)key[i * 4 + 3] << 24);
  for (int i = 0; i < 3; i++)
    n[i] = (uint32_t)nonce[i * 4] | ((uint32_t)nonce[i * 4 + 1] << 8) |
           ((uint32_t)nonce[i * 4 + 2] << 16) | ((uint32_t)nonce[i * 4 + 3] << 24);

  uint32_t counter = 1;
  uint8_t keystream[64];
  size_t offset = 0;

  while (offset < input_len) {
    chacha20_block(k, counter++, n, keystream);
    size_t chunk = (input_len - offset > 64) ? 64 : (input_len - offset);
    for (size_t i = 0; i < chunk; i++)
      output[offset + i] = input[offset + i] ^ keystream[i];
    offset += chunk;
  }
  return offset;
}

// ============================================================================
// 生成随机密钥
// ============================================================================

static void generate_random_key(uint8_t key[32], uint8_t nonce[12]) {
  std::random_device rd;
  std::mt19937 gen(rd());
  std::uniform_int_distribution<uint32_t> dist(0, 255);
  for (int i = 0; i < 32; i++) key[i] = dist(gen);
  for (int i = 0; i < 12; i++) nonce[i] = dist(gen);
}

// ============================================================================
// 生成 payload.h
// ============================================================================

static bool generatePayloadH(const std::string &output_path,
                              const uint8_t *encrypted_data, size_t encrypted_size,
                              const uint8_t key[32], const uint8_t nonce[12],
                              const std::string &env_key) {
  std::error_code EC;
  raw_fd_ostream OS(output_path, EC, sys::fs::OF_None);
  if (EC) {
    errs() << "Error: Cannot write payload.h: " << EC.message() << "\n";
    return false;
  }

  OS << "/*\n";
  OS << " * ChaCha20 encrypted payload - auto generated by clang -irobf-linker\n";
  OS << " * Original size: " << encrypted_size << " bytes\n";
  OS << " */\n\n";
  OS << "#ifndef PAYLOAD_H\n";
  OS << "#define PAYLOAD_H\n\n";
  OS << "#include <stdint.h>\n";
  OS << "#include <stddef.h>\n\n";
  OS << "#define PAYLOAD_RAW_SIZE " << encrypted_size << "u\n\n";

  OS << "#define CHACHA20_KEY {";
  for (int i = 0; i < 32; i++) {
    OS << "0x" << format_hex_no_prefix(key[i], 2);
    if (i < 31) OS << ",";
  }
  OS << "}\n\n";

  OS << "#define CHACHA20_NONCE {";
  for (int i = 0; i < 12; i++) {
    OS << "0x" << format_hex_no_prefix(nonce[i], 2);
    if (i < 11) OS << ",";
  }
  OS << "}\n\n";

  OS << "static const uint8_t payload_data[] = {\n";
  for (size_t i = 0; i < encrypted_size; i++) {
    if (i % 16 == 0) OS << "    ";
    OS << "0x" << format_hex_no_prefix(encrypted_data[i], 2);
    if (i < encrypted_size - 1) OS << ", ";
    if (i % 16 == 15 || i == encrypted_size - 1) OS << "\n";
  }
  OS << "};\n";
  OS << "static const size_t payload_data_size = " << encrypted_size << ";\n\n";

  // 环境变量密钥（壳程序设置 lc=<env_key>，内嵌检测代码校验）
  OS << "#define ENV_KEY \"" << env_key << "\"\n\n";

  OS << "#endif // PAYLOAD_H\n";
  OS.flush();
  return true;
}

// ============================================================================
// 生成 loader.cpp 壳源码
// ============================================================================

static bool generateLoaderCpp(const std::string &output_path) {
  std::error_code EC;
  raw_fd_ostream OS(output_path, EC, sys::fs::OF_None);
  if (EC) {
    errs() << "Error: Cannot write loader.cpp: " << EC.message() << "\n";
    return false;
  }

  OS << R"(/*
 * ARM64 ELF 内存加载器 - ChaCha20 解密 + fork 执行 + 擦除 ELF 头 + 反调试
 * 自动生成，由 clang -irobf-linker 产生
 */

#include <stdint.h>
#include <stddef.h>
#include <string.h>
#include <stdlib.h>

#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <sys/ptrace.h>
#include <unistd.h>
#include <dlfcn.h>
#include <fcntl.h>
#include <errno.h>
#include <signal.h>
#include <pthread.h>
#include <android/log.h>

#include "payload.h"

#define LOG_TAG "ELFLoader"

static inline uint32_t rotl32(uint32_t v, int n) {
    return (v << n) | (v >> (32 - n));
}

static inline void qr(uint32_t* s, int a, int b, int c, int d) {
    s[a] += s[b]; s[d] ^= s[a]; s[d] = rotl32(s[d], 16);
    s[c] += s[d]; s[b] ^= s[c]; s[b] = rotl32(s[b], 12);
    s[a] += s[b]; s[d] ^= s[a]; s[d] = rotl32(s[d], 8);
    s[c] += s[d]; s[b] ^= s[c]; s[b] = rotl32(s[b], 7);
}

static void chacha20_block(const uint32_t key[8], uint32_t counter,
                           const uint32_t nonce[3], uint8_t out[64]) {
    uint32_t s[16] = {
        0x61707865, 0x3320646e, 0x79622d32, 0x6b206574,
        key[0], key[1], key[2], key[3],
        key[4], key[5], key[6], key[7],
        counter, nonce[0], nonce[1], nonce[2]
    };
    uint32_t w[16];
    memcpy(w, s, sizeof(w));
    for (int i = 0; i < 10; i++) {
        qr(w, 0, 4,  8, 12); qr(w, 1, 5,  9, 13);
        qr(w, 2, 6, 10, 14); qr(w, 3, 7, 11, 15);
        qr(w, 0, 5, 10, 15); qr(w, 1, 6, 11, 12);
        qr(w, 2, 7,  8, 13); qr(w, 3, 4,  9, 14);
    }
    for (int i = 0; i < 16; i++) {
        uint32_t val = w[i] + s[i];
        out[i*4+0]=(uint8_t)(val); out[i*4+1]=(uint8_t)(val>>8);
        out[i*4+2]=(uint8_t)(val>>16); out[i*4+3]=(uint8_t)(val>>24);
    }
}

static size_t chacha20_decrypt(const uint8_t* input, size_t input_len,
                               const uint8_t key[32], const uint8_t nonce[12],
                               uint8_t* output) {
    uint32_t k[8], n[3];
    for (int i = 0; i < 8; i++)
        k[i] = (uint32_t)key[i*4]|((uint32_t)key[i*4+1]<<8)|((uint32_t)key[i*4+2]<<16)|((uint32_t)key[i*4+3]<<24);
    for (int i = 0; i < 3; i++)
        n[i] = (uint32_t)nonce[i*4]|((uint32_t)nonce[i*4+1]<<8)|((uint32_t)nonce[i*4+2]<<16)|((uint32_t)nonce[i*4+3]<<24);
    uint32_t counter = 1;
    uint8_t keystream[64];
    size_t offset = 0;
    while (offset < input_len) {
        chacha20_block(k, counter++, n, keystream);
        size_t chunk = (input_len - offset > 64) ? 64 : (input_len - offset);
        for (size_t i = 0; i < chunk; i++)
            output[offset + i] = input[offset + i] ^ keystream[i];
        offset += chunk;
    }
    return offset;
}

// ============================================================================
// 反调试：读取指定进程的 TracerPid
// ============================================================================
static pid_t get_tracerpid_of(pid_t pid) {
    char path[64];
    snprintf(path, sizeof(path), "/proc/%d/status", pid);
    int fd = open(path, O_RDONLY);
    if (fd < 0) return -1;
    char buf[4096];
    ssize_t n = read(fd, buf, sizeof(buf) - 1);
    close(fd);
    if (n <= 0) return -1;
    buf[n] = '\0';
    const char* tag = "TracerPid:\t";
    char* p = strstr(buf, tag);
    if (!p) return -1;
    p += strlen(tag);
    return (pid_t)atoi(p);
}

// ============================================================================
// 反调试：父进程作为 tracer 持续监控子进程
// 子进程 execv 前调用 PTRACE_TRACEME，exec 后 trace 关系保持
// 外部进程无法再 ptrace 附加子进程
// ============================================================================
static void* anti_debug_thread(void* arg) {
    pid_t child = *(pid_t*)arg;

    for (;;) {
        // 检测子进程的 TracerPid
        // 正常情况：TracerPid == 父进程 PID（我们正在 trace 它）
        // 异常情况：TracerPid == 0（trace 关系被断开，被反调试绕过）
        pid_t tracer = get_tracerpid_of(child);
        if (tracer == 0) {
            // TracerPid 为 0：trace 关系被断开，杀掉子进程
            kill(child, SIGKILL);
            _exit(9);
        }
        usleep(200000);
    }
    return NULL;
}

// ============================================================================
// ELF 头擦除
// ============================================================================
static bool erase_elf_header(pid_t pid, const char* target_path) {
    char maps_path[64];
    snprintf(maps_path, sizeof(maps_path), "/proc/%d/maps", pid);
    FILE* maps = fopen(maps_path, "r");
    if (!maps) return false;
    uint64_t base_addr = 0;
    char line[512];
    while (fgets(line, sizeof(line), maps)) {
        if (strstr(line, target_path) && strstr(line, "r-xp")) {
            unsigned long long start, end;
            if (sscanf(line, "%llx-%llx", &start, &end) == 2) { base_addr = start; break; }
        }
    }
    fclose(maps);
    if (base_addr == 0) return false;
    char mem_path[64];
    snprintf(mem_path, sizeof(mem_path), "/proc/%d/mem", pid);
    int mem_fd = open(mem_path, O_WRONLY);
    if (mem_fd < 0) return false;
    uint8_t zero_header[64] = {};
    pwrite(mem_fd, zero_header, sizeof(zero_header), (off_t)base_addr);
    close(mem_fd);
    return true;
}

static char g_temp_path[256] = {};
static pid_t g_child_pid = -1;
static char g_env_key[33] = {};

static bool do_load(const uint8_t* encrypted_data, size_t encrypted_size) {
    uint8_t* decrypted = (uint8_t*)malloc(encrypted_size);
    if (!decrypted) return false;
    const uint8_t key[] = CHACHA20_KEY;
    const uint8_t nonce[] = CHACHA20_NONCE;
    chacha20_decrypt(encrypted_data, encrypted_size, key, nonce, decrypted);
    char temp_template[] = "/data/local/tmp/.ld_XXXXXX";
    int fd = mkstemp(temp_template);
    if (fd < 0) { free(decrypted); return false; }
    strncpy(g_temp_path, temp_template, sizeof(g_temp_path) - 1);
    write(fd, decrypted, encrypted_size);
    close(fd);
    free(decrypted);
    chmod(g_temp_path, 0755);
    return true;
}

static int do_execute(int argc, char** argv) {
    if (g_temp_path[0] == '\0') return -1;
    pid_t pid = fork();
    if (pid < 0) return -1;
    if (pid == 0) {
        // 子进程：PTRACE_TRACEME 让父进程 trace 自己
        // execv 后 trace 关系保持，外部进程无法再 ptrace 附加
        ptrace(PTRACE_TRACEME, 0, NULL, NULL);
        // 设置环境变量 lc，供内嵌的 EnvCheck Pass 校验
        setenv("lc", g_env_key, 1);
        execv(g_temp_path, argv);
        _exit(127);
    }
    g_child_pid = pid;

    // 父进程：等待子进程 exec 产生的 SIGTRAP
    int status = 0;
    waitpid(pid, &status, 0);
    if (WIFEXITED(status)) return WEXITSTATUS(status);

    // 子进程已停在 exec 的 SIGTRAP，继续运行
    ptrace(PTRACE_CONT, pid, NULL, NULL);

    // 擦除 ELF 头
    erase_elf_header(pid, g_temp_path);

    // 启动反调试监控线程：持续检测子进程 TracerPid
    static pid_t child_pid_copy;
    child_pid_copy = pid;
    pthread_t tid;
    pthread_create(&tid, NULL, anti_debug_thread, &child_pid_copy);
    pthread_detach(tid);

    // 等待子进程结束
    waitpid(pid, &status, 0);
    if (WIFEXITED(status)) return WEXITSTATUS(status);
    if (WIFSIGNALED(status)) return -WTERMSIG(status);
    return -1;
}

int main(int argc, char* argv[]) {
    // 初始化环境变量密钥
    const char* ek = ENV_KEY;
    strncpy(g_env_key, ek, sizeof(g_env_key) - 1);
    g_env_key[sizeof(g_env_key) - 1] = '\0';

    if (!do_load(payload_data, payload_data_size)) return 1;
    int result = do_execute(argc, argv);
    if (g_temp_path[0] != '\0') unlink(g_temp_path);
    return result;
}
)";
  OS.flush();
  return true;
}

// ============================================================================
// 执行 ELF 加壳
// ============================================================================

bool clang::driver::performELFWrapping(const std::string &InputELF,
                                const std::string &OutputPath,
                                const std::string &TargetTriple,
                                const std::string &ClangPath,
                                const std::string &Sysroot,
                                bool DebugMode) {
  // 1. 读取原始 ELF 文件
  std::ifstream in(InputELF, std::ios::binary | std::ios::ate);
  if (!in.is_open()) {
    errs() << "Error: [irobf-linker] Cannot open input ELF: " << InputELF << "\n";
    return false;
  }
  size_t file_size = in.tellg();
  in.seekg(0, std::ios::beg);

  std::vector<uint8_t> elf_data(file_size);
  if (!in.read(reinterpret_cast<char *>(elf_data.data()), file_size)) {
    errs() << "Error: [irobf-linker] Cannot read input ELF\n";
    return false;
  }
  in.close();

  // 验证 ELF 魔数
  if (elf_data.size() < 4 || elf_data[0] != 0x7f || elf_data[1] != 'E' ||
      elf_data[2] != 'L' || elf_data[3] != 'F') {
    errs() << "Warning: [irobf-linker] Input is not a valid ELF, skipping wrapper\n";
    // 不是 ELF，直接复制原文件
    sys::fs::copy_file(InputELF, OutputPath);
    return true;
  }

  if (DebugMode) outs() << "[irobf-linker] Wrapping ELF: " << file_size << " bytes\n";

  // 获取 clang 所在目录
  SmallString<128> clangDir;
  {
    SmallString<128> absClangPath(ClangPath);
    sys::fs::make_absolute(absClangPath);
    clangDir = sys::path::parent_path(absClangPath);
  }

  // 使用 llvm-strip 剥离符号表
  SmallString<256> llvmStripPath;
  sys::path::append(llvmStripPath, clangDir, "llvm-strip");
#ifdef _WIN32
  sys::path::replace_extension(llvmStripPath, "exe");
#endif
  if (sys::fs::exists(llvmStripPath)) {
    // 创建临时文件用于存储剥离符号后的 ELF
    SmallString<256> strippedPath;
    sys::path::append(strippedPath, clangDir, ".linker_stripped");
    
    SmallVector<StringRef, 8> stripArgs;
    stripArgs.push_back(llvmStripPath);
    stripArgs.push_back("--strip-unneeded");
    stripArgs.push_back("-o");
    stripArgs.push_back(strippedPath);
    stripArgs.push_back(InputELF);
    
    std::string stripErrMsg;
    int stripRet = sys::ExecuteAndWait(llvmStripPath, stripArgs, {}, {}, 0, 0, &stripErrMsg);
    if (stripRet == 0) {
      // 重新读取剥离符号后的文件
      std::ifstream strippedFile(std::string(strippedPath.str()));
      if (strippedFile.is_open()) {
        strippedFile.seekg(0, std::ios::end);
        file_size = strippedFile.tellg();
        strippedFile.seekg(0, std::ios::beg);
        elf_data.resize(file_size);
        strippedFile.read(reinterpret_cast<char *>(elf_data.data()), file_size);
        strippedFile.close();
        if (DebugMode) outs() << "[irobf-linker] Stripped symbols, new size: " << file_size << " bytes\n";
      }
      sys::fs::remove(strippedPath);
    } else {
      if (DebugMode) outs() << "[irobf-linker] Warning: llvm-strip failed, using original ELF\n";
    }
  }

  // 2. 生成随机密钥并加密
  uint8_t key[32], nonce[12];
  generate_random_key(key, nonce);

  // 从 clang 同目录的 .linker_env_key 文件读取密钥（由 EnvCheck Pass 生成）
  SmallString<256> linkerKeyPath;
  sys::path::append(linkerKeyPath, clangDir, ".linker_env_key");
  std::string linkerKeyPathStr = std::string(linkerKeyPath.str());
  std::string env_key(32, '\0');
  {
    std::ifstream keyFile(linkerKeyPathStr);
    if (keyFile.is_open()) {
      keyFile.read(&env_key[0], 32);
      keyFile.close();
      if (DebugMode) outs() << "[irobf-linker] Read key from " << linkerKeyPath << ": " << env_key << "\n";
    } else {
      // 如果文件不存在，生成随机密钥
      if (DebugMode) outs() << "[irobf-linker] Warning: " << linkerKeyPath << " not found, generating random key\n";
      std::random_device rd;
      std::mt19937 gen(rd());
      std::uniform_int_distribution<int> dist(0, 15);
      const char hex[] = "0123456789abcdef";
      for (int i = 0; i < 32; i++)
        env_key[i] = hex[dist(gen)];
    }
  }

  std::vector<uint8_t> encrypted_data(file_size);
  chacha20_encrypt(elf_data.data(), file_size, key, nonce, encrypted_data.data());

  // 3. 创建临时目录
  SmallString<128> tmp_dir;
  std::error_code EC = sys::fs::createUniqueDirectory("elf-wrapper", tmp_dir);
  if (EC) {
    errs() << "Error: [irobf-linker] Cannot create temp directory: " << EC.message() << "\n";
    return false;
  }

  std::string payload_h_path = (tmp_dir + "/payload.h").str();
  std::string loader_cpp_path = (tmp_dir + "/loader.cpp").str();
  std::string wrapped_elf_path = (tmp_dir + "/wrapped.elf").str();

  // 4. 生成 payload.h 和 loader.cpp
  if (!generatePayloadH(payload_h_path, encrypted_data.data(), file_size, key, nonce, env_key)) {
    sys::fs::remove_directories(tmp_dir);
    return false;
  }

  if (!generateLoaderCpp(loader_cpp_path)) {
    sys::fs::remove_directories(tmp_dir);
    return false;
  }

  // 规范化路径（去掉 .. 等，统一使用绝对路径）
  std::string normalized_clang, normalized_sysroot;
  SmallString<128> abs_path(ClangPath);
  sys::fs::make_absolute(abs_path);
  sys::path::remove_dots(abs_path, /*remove_dot_dot=*/true);
  normalized_clang = std::string(abs_path);

  if (!Sysroot.empty()) {
    abs_path = Sysroot;
    sys::fs::make_absolute(abs_path);
    sys::path::remove_dots(abs_path, /*remove_dot_dot=*/true);
    normalized_sysroot = std::string(abs_path);
  }

  // 5. 编译壳程序 - 调用 clang 自身，最高强度混淆
  std::string compile_cmd =
      "\"" + normalized_clang + "\""
      + " -target " + TargetTriple;
  if (!normalized_sysroot.empty())
    compile_cmd += " --sysroot=\"" + normalized_sysroot + "\"";
  compile_cmd +=
      std::string(" -O2 -std=c++17 -fno-exceptions -frtti")
      // 最高强度混淆
      + " -mllvm -irobf"
      + " -mllvm -irobf-indbr -mllvm -level-indbr=3"
      + " -mllvm -irobf-icall -mllvm -level-icall=3"
      + " -mllvm -irobf-fla"
      + " -mllvm -irobf-indgv -mllvm -level-indgv=3"
      + " -mllvm -irobf-cse"
      + " -mllvm -irobf-cie -mllvm -level-cie=3"
      + " -mllvm -irobf-cfe -mllvm -level-cfe=3"
      + " -mllvm -irobf-rtti"
      + " -mllvm -irobf-syscall"
      + " -lm -ldl -llog"
      + " -o \"" + wrapped_elf_path + "\""
      + " \"" + loader_cpp_path + "\""
      + " -I\"" + std::string(tmp_dir.str()) + "\"";

  if (DebugMode) outs() << "[irobf-linker] Compiling wrapper with max obfuscation...\n";

  // 使用 llvm::sys::ExecuteAndWait 替代 system()，避免 Windows cmd.exe 路径问题
  SmallVector<StringRef, 64> argv;
  argv.push_back(normalized_clang);
  argv.push_back("-target");
  argv.push_back(TargetTriple);
  if (!normalized_sysroot.empty()) {
    argv.push_back("--sysroot");
    argv.push_back(normalized_sysroot);
  }
  argv.push_back("-O2");
  argv.push_back("-std=c++17");
  argv.push_back("-fno-exceptions");
  argv.push_back("-frtti");
  // 最高强度混淆
  argv.push_back("-mllvm"); argv.push_back("-irobf");
  argv.push_back("-mllvm"); argv.push_back("-irobf-indbr");
  argv.push_back("-mllvm"); argv.push_back("-level-indbr=3");
  argv.push_back("-mllvm"); argv.push_back("-irobf-icall");
  argv.push_back("-mllvm"); argv.push_back("-level-icall=3");
  argv.push_back("-mllvm"); argv.push_back("-irobf-fla");
  argv.push_back("-mllvm"); argv.push_back("-irobf-indgv");
  argv.push_back("-mllvm"); argv.push_back("-level-indgv=3");
  argv.push_back("-mllvm"); argv.push_back("-irobf-cse");
  argv.push_back("-mllvm"); argv.push_back("-irobf-cie");
  argv.push_back("-mllvm"); argv.push_back("-level-cie=3");
  argv.push_back("-mllvm"); argv.push_back("-irobf-cfe");
  argv.push_back("-mllvm"); argv.push_back("-level-cfe=3");
  argv.push_back("-mllvm"); argv.push_back("-irobf-rtti");
  argv.push_back("-mllvm"); argv.push_back("-irobf-syscall");
  argv.push_back("-lm");
  argv.push_back("-ldl");
  argv.push_back("-llog");
  argv.push_back("-o");
  argv.push_back(wrapped_elf_path);
  argv.push_back(loader_cpp_path);
  std::string include_arg = "-I" + std::string(tmp_dir.str());
  argv.push_back(include_arg);

  std::string errMsg;
  int ret = sys::ExecuteAndWait(normalized_clang, argv, {},
                                 {}, 0, 0, &errMsg);

  if (ret != 0) {
    errs() << "Error: [irobf-linker] Wrapper compilation failed (code: " << ret << ")";
    if (!errMsg.empty()) errs() << ": " << errMsg;
    errs() << "\n";
    sys::fs::remove_directories(tmp_dir);
    return false;
  }

  // 6. 复制到输出路径
  EC = sys::fs::copy_file(wrapped_elf_path, OutputPath);
  if (EC) {
    errs() << "Error: [irobf-linker] Cannot copy to output: " << EC.message() << "\n";
    sys::fs::remove_directories(tmp_dir);
    return false;
  }

  // 设置可执行权限
  sys::fs::setPermissions(OutputPath, sys::fs::perms::all_read |
                                          sys::fs::perms::all_write |
                                          sys::fs::perms::owner_exe |
                                          sys::fs::perms::group_exe |
                                          sys::fs::perms::others_exe);

  // 清理临时文件
  sys::fs::remove_directories(tmp_dir);
  // 删除链接器输出的临时文件
  sys::fs::remove(InputELF);
  // 删除密钥文件
  sys::fs::remove(linkerKeyPath);

  if (DebugMode) outs() << "[irobf-linker] Done! Wrapped ELF: " << OutputPath << "\n";
  return true;
}

// ============================================================================
// Base64 编码
// ============================================================================

static const char base64_table[] =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

static std::string base64_encode(const uint8_t *data, size_t len) {
  std::string result;
  result.reserve((len + 2) / 3 * 4);
  for (size_t i = 0; i < len; i += 3) {
    uint32_t n = (uint32_t)data[i] << 16;
    if (i + 1 < len) n |= (uint32_t)data[i + 1] << 8;
    if (i + 2 < len) n |= (uint32_t)data[i + 2];
    result.push_back(base64_table[(n >> 18) & 0x3F]);
    result.push_back(base64_table[(n >> 12) & 0x3F]);
    result.push_back((i + 1 < len) ? base64_table[(n >> 6) & 0x3F] : '=');
    result.push_back((i + 2 < len) ? base64_table[n & 0x3F] : '=');
  }
  return result;
}

// ============================================================================
// gzip 压缩（使用 LLVM 内置 zlib 支持）
// ============================================================================

static bool gzip_compress(const uint8_t *input, size_t input_len,
                          std::vector<uint8_t> &output) {
  if (!compression::zlib::isAvailable()) {
    errs() << "Error: [irobf-gz] zlib not available in this build\n";
    return false;
  }
  SmallVector<uint8_t, 0> compressed;
  compression::zlib::compress(ArrayRef<uint8_t>(input, input_len),
                              compressed,
                              compression::zlib::BestSizeCompression);
  output.assign(compressed.begin(), compressed.end());
  return true;
}

// ============================================================================
// 执行 gzip+base64 压缩壳（生成 shell 脚本）
// ============================================================================

bool clang::driver::performGzWrapping(const std::string &InputELF,
                                      const std::string &OutputPath,
                                      const std::string &TargetTriple,
                                      const std::string &ClangPath,
                                      const std::string &Sysroot,
                                      bool DebugMode) {
  // 1. 读取输入 ELF 文件
  std::ifstream in(InputELF, std::ios::binary | std::ios::ate);
  if (!in.is_open()) {
    errs() << "Error: [irobf-gz] Cannot open input ELF: " << InputELF << "\n";
    return false;
  }
  size_t file_size = in.tellg();
  in.seekg(0, std::ios::beg);

  std::vector<uint8_t> elf_data(file_size);
  if (!in.read(reinterpret_cast<char *>(elf_data.data()), file_size)) {
    errs() << "Error: [irobf-gz] Cannot read input ELF\n";
    return false;
  }
  in.close();

  // 验证 ELF 魔数
  if (elf_data.size() < 4 || elf_data[0] != 0x7f || elf_data[1] != 'E' ||
      elf_data[2] != 'L' || elf_data[3] != 'F') {
    errs() << "Warning: [irobf-gz] Input is not a valid ELF, skipping wrapper\n";
    sys::fs::copy_file(InputELF, OutputPath);
    return true;
  }

  if (DebugMode) outs() << "[irobf-gz] Compressing ELF: " << file_size << " bytes\n";

  // 获取 clang 所在目录
  SmallString<128> clangDir;
  {
    SmallString<128> absClangPath(ClangPath);
    sys::fs::make_absolute(absClangPath);
    clangDir = sys::path::parent_path(absClangPath);
  }

  // 使用 llvm-strip 剥离符号表
  SmallString<256> llvmStripPath;
  sys::path::append(llvmStripPath, clangDir, "llvm-strip");
#ifdef _WIN32
  sys::path::replace_extension(llvmStripPath, "exe");
#endif
  if (sys::fs::exists(llvmStripPath)) {
    // 创建临时文件用于存储剥离符号后的 ELF
    SmallString<256> strippedPath;
    sys::path::append(strippedPath, clangDir, ".gz_stripped");
    
    SmallVector<StringRef, 8> stripArgs;
    stripArgs.push_back(llvmStripPath);
    stripArgs.push_back("--strip-unneeded");
    stripArgs.push_back("-o");
    stripArgs.push_back(strippedPath);
    stripArgs.push_back(InputELF);
    
    std::string stripErrMsg;
    int stripRet = sys::ExecuteAndWait(llvmStripPath, stripArgs, {}, {}, 0, 0, &stripErrMsg);
    if (stripRet == 0) {
      // 重新读取剥离符号后的文件
      std::ifstream strippedFile(std::string(strippedPath.str()));
      if (strippedFile.is_open()) {
        strippedFile.seekg(0, std::ios::end);
        file_size = strippedFile.tellg();
        strippedFile.seekg(0, std::ios::beg);
        elf_data.resize(file_size);
        strippedFile.read(reinterpret_cast<char *>(elf_data.data()), file_size);
        strippedFile.close();
        if (DebugMode) outs() << "[irobf-gz] Stripped symbols, new size: " << file_size << " bytes\n";
      }
      sys::fs::remove(strippedPath);
    } else {
      if (DebugMode) outs() << "[irobf-gz] Warning: llvm-strip failed, using original ELF\n";
    }
  }

  // 从 clang 同目录的 .gz_env_key 文件读取密钥（由 GzEnvCheck Pass 生成）
  SmallString<256> gzKeyPath;
  sys::path::append(gzKeyPath, clangDir, ".gz_env_key");
  std::string gzKeyPathStr = std::string(gzKeyPath.str());
  std::string gz_env_key(32, '\0');
  {
    std::ifstream keyFile(gzKeyPathStr);
    if (keyFile.is_open()) {
      keyFile.read(&gz_env_key[0], 32);
      keyFile.close();
      if (DebugMode) outs() << "[irobf-gz] Read key from " << gzKeyPath << ": " << gz_env_key << "\n";
    } else {
      // 如果文件不存在，生成随机密钥
      if (DebugMode) outs() << "[irobf-gz] Warning: " << gzKeyPath << " not found, generating random key\n";
      std::random_device rd;
      std::mt19937 gen(rd());
      std::uniform_int_distribution<int> dist(0, 15);
      const char hex[] = "0123456789abcdef";
      for (int i = 0; i < 32; i++)
        gz_env_key[i] = hex[dist(gen)];
    }
  }

  // 生成随机 EOF 标志
  std::string eof_marker;
  {
    std::random_device rd;
    std::mt19937 gen(rd());
    std::uniform_int_distribution<int> dist(0, 61);
    const char chars[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    for (int i = 0; i < 16; i++)
      eof_marker += chars[dist(gen)];
  }

  // 3. base64 编码（跳过 gzip 压缩，直接编码原始 ELF）
  std::string b64_data = base64_encode(elf_data.data(), file_size);
  if (DebugMode) outs() << "[irobf-gz] Base64 encoded: " << b64_data.size() << " bytes\n";

  // 4. 生成 shell 脚本
  std::error_code EC;
  raw_fd_ostream OS(OutputPath, EC, sys::fs::OF_None);
  if (EC) {
    errs() << "Error: [irobf-gz] Cannot write output: " << EC.message() << "\n";
    return false;
  }

  // Shell 脚本头部
  OS << "#!/system/bin/sh\n";
  OS << "# By.abcdefgjh 给小辈一个面子，别破解了，相信大牛你的实力了\n\n";

  // 解码并执行
  OS << "TMPFILE=\"/data/local/tmp/.gz_$$\"\n";
  OS << "base64 -d << '" << eof_marker << "' > \"$TMPFILE\" 2>/dev/null\n";

  // 写入 base64 数据（每行 76 字符）
  const size_t line_width = 76;
  for (size_t i = 0; i < b64_data.size(); i += line_width) {
    size_t end = std::min(i + line_width, b64_data.size());
    OS << StringRef(b64_data.data() + i, end - i) << "\n";
  }

  OS << eof_marker << "\n\n";

  // 设置环境变量（数据之后、启动之前）
  OS << "export lc_gz=\"" << gz_env_key << "\"\n\n";

  // 执行
  OS << "chmod 777 \"$TMPFILE\"\n";
  OS << "exec \"$TMPFILE\" \"$@\"\n";
  OS << "rm -f \"$TMPFILE\"\n";

  OS.flush();

  // 设置可执行权限
  sys::fs::setPermissions(OutputPath, sys::fs::perms::all_read |
                                          sys::fs::perms::all_write |
                                          sys::fs::perms::owner_exe |
                                          sys::fs::perms::group_exe |
                                          sys::fs::perms::others_exe);

  // 删除输入文件
  sys::fs::remove(InputELF);
  // 删除密钥文件
  sys::fs::remove(gzKeyPath);

  if (DebugMode) outs() << "[irobf-gz] Done! Shell wrapper: " << OutputPath << "\n";
  return true;
}
